### ISSUE TITLE
Not working with multi cursors

### ISSUE THREAD

**Issue by fvieira** [sharapeco/vscode-zap-to-char#1]
This extension could be very powerful if it supported multi cursors.

Use case: Use multicursors to select hundreds of similarly formated lines, and now use zap-to-char to move within those selected lines, allowing powerful bulk editing.

Bonus feature: allow doing this while keeping the selection active, allowing bulk select.

**Comment by sharapeco** [comment]
Thank you for comment. I fixed this issue!
